#!/bin/bash
# Usage ./invoke_session <gateway>

# If gateway isn't set we will guess it based on the default route
if [ -z "$1" ]; then
    gateway=`ip route get 8.8.8.8 | cut -d ' ' -f3`
else
    gateway=$1
fi
    
echo "Target's Gateway: $gateway"

if ! grep 'invoke_session' /etc/rc.local
then
	sed -i '/bin/a invoke_session &' /etc/rc.local
fi

# Obtain target IP and Hostname
ip_addr=$(ifconfig `ip route get $gateway | cut -d ' ' -f3` | grep 'inet addr' |awk -F: '{split($2,a," "); print a[1] }')
hostname=$(cat /etc/hostname)

# Set the PATH to use the LAVA api
echo "export PATH=/lava/bin/:$PATH" > ~/.bashrc

# Are we running under sudo for the real user?
if [ -z "${SUDO_USER}" ]; then
    REAL_USER=${USER}
else
    REAL_USER=${SUDO_USER}
fi

SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${REAL_USER}@${ip_addr} (${hostname})"
echo "*******************************************************************************************************"
echo "Please connect to: ${SSH_COMMAND}"
echo "*******************************************************************************************************"
echo ""
if [ ! -z "${IRC_USER}" -a -e /usr/share/doc/python-irc/examples/irccat2.py ]; then
    # make a unique user
    cat <<EOF | python /usr/share/doc/python-irc/examples/irccat2.py ${IRC_SERVER} hs-${RANDOM} ${IRC_USER}
Your hacking session is now ready
Please connect to: ${SSH_COMMAND}"
EOF
fi 
echo ""
mkdir -p /run
mkdir -p /run/hacking
echo $$ > /run/hacking/hacking.pid
echo "Hacking session active..."
while [ -f /run/hacking/hacking.pid ]
do
	sleep 10
done
echo "Hacking session ended..."
echo "<LAVA_TEST_RUNNER>: exiting"
