#!/bin/sh
# Usage ./setup_session <pub_key>

chmod a+x stop_hacking_oe
cp stop_hacking_oe /bin/stop_hacking
chmod a+x invoke_session_oe
cp invoke_session_oe /bin/invoke_session

mkdir -p ~/.ssh/
echo $1 >> ~/.ssh/authorized_keys
echo "Public Key Installed: $1"

/etc/init.d/sshd restart
echo "sshd re-started"
